version: '3.9'
services:
  # db:
  #   image: postgres:latest
  #   ports:
  #     - 5432:${DB_PORT}
  #   environment:
  #     - POSTGRES_USER=${DB_USER}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  app:
    container_name: api-aimarket
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:${PORT}
    env_file:
      - .env
    # depends_on:
    #   - db
    # environment:
    #   - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
